version: '3'

services:
  nginx-puma:
    labels:
      # standardnotes
      - "traefik.enable=true"
      - "traefik.http.routers.standardnotes.rule=Host(`${FQDN}`)"
      - "traefik.http.routers.standardnotes.entrypoints=websecure"
      - "traefik.http.services.standardnotes.loadbalancer.server.port=80"
      - "traefik.http.routers.standardnotes.service=standardnotes"
      - "traefik.http.routers.standardnotes.tls=true"
      - "traefik.http.routers.standardnotes.tls.certresolver=lets-encrypt"
      # sync
      - "traefik.http.routers.sync.rule=Host(`${FQDN1}`)"
      - "traefik.http.routers.sync.entrypoints=websecure"
      - "traefik.http.services.sync.loadbalancer.server.port=3125"
      - "traefik.http.routers.sync.service=sync"
      - "traefik.http.routers.sync.tls=true"
      - "traefik.http.routers.sync.tls.certresolver=lets-encrypt"
    networks:
      - nextcloud
      - internal

  app:
    networks:
      - internal

  localstack:
    networks:
      - internal

  db:
    networks:
      - internal

  cache:
    networks:
      - internal

networks:
  nextcloud:
    external: true
  internal:
    external: false
